[package]
name = "http2"
version = "1.0.0"
publish = false
edition.workspace = true

# <deps>
[dependencies]
actix-web = { version = "4", features = ["rustls-0_23"] }
rustls = "0.23"
rustls-pemfile = "2"
# </deps>
