[package]
name = "my_errors"
version = "1.0.0"
publish = false
edition.workspace = true

[dependencies]
actix-web = "4"
derive_more = { version = "2", features = ["display", "error"] }
env_logger = "0.11"
log = "0.4"
