language: rust
sudo: false

install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.tar.gz |
      tar xzvf -

script:
  - ./hugo_0.40.3_Linux-64bit/hugo_0.18.1_linux_amd64

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"
