sudo: false

env:
  global:
    - OPENSSL_VERSION=openssl-1.0.2

before_install:
  - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
  - sudo apt-get update -qq
  - sudo apt-get install -qq libssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev

cache:
  directories:
    - $HOME/cargo
    - $TRAVIS_BUILD_DIR/examples/target

install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.tar.gz | tar xzvf -

matrix:
  include:
    - env:
      - TASK=build
      script: ./hugo
    - env:
      - TASK=check
      language: rust
      script: cd examples; cargo check

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false" && $TASK = "build"
