title = "actix"
canonifyURLs = true
googleAnalytics = "UA-110322332-1"
pygmentsUseClasses = true
pygmentsCodeFences = true
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true
DefaultContentLanguage = "en"
baseURL = "https://actix.rs"

[languages.en]
  languageCode = "en-US"
  languageName = "English"
  weight = 1

[params]
actixVersion = "0.9"
actixWebVersion = "2.0"
actixRtVersion = "1.0"
actixWebMinRustVersion = "1.36"
actixMinRustVersion = "1.31"
