[package]
name = "middleware"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
env_logger = "0.7"
