[package]
name = "shuttle"
version = "1.0.0"
publish = false
edition.workspace = true

# <shuttle-deps>
[dependencies]
actix-web = "4"
shuttle-actix-web = "0.56"
shuttle-runtime = "0.56"
tokio = "1"
# </shuttle-deps>
